export const students = [
    {
        student_id: 1788,
        cpr: '071001026',
        registration_date: "1/13/2019",
        first_name: "Mohamed Hussain",
        additional_names: "Mohamed Jawad Taha",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 6,
        school_name: 'budaya',
    },
    {
        student_id: 1788,
        cpr: '071001026',
        registration_date: "1/13/2019",
        first_name: "Mohamed Hussain",
        additional_names: "Mohamed Jawad Taha",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 6,
        school_name: 'budaya',
    },
    {
        student_id: 791,
        cpr: '980408032',
        registration_date: "1/13/2019",
        first_name: "Mariam",
        additional_names: "Abaas Mohammed Habib",
        gender: "F",
        birthdate: "10/7/2007",
        school_grade: "Pri 6",
        school_name: 'budaya',
    },
    {
        student_id: 1213,
        cpr: '091005515',
        registration_date: "2/21/2017",
        first_name: "Abdulla",
        additional_names: "Abbas Abdulla Ahmed Jassim",
        gender: "M",
        birthdate: "10/8/2009",
        school_grade: "Pri 2",
        school_name: "Barbar Primary School",
    },
    {
        student_id: 435,
        cpr: '080604617',
        registration_date: "10/13/2018",
        first_name: "Kawthar",
        additional_names: "Abbas Abdulla Ali",
        gender: "F",
        birthdate: "6/14/2008",
        school_grade: "Pri 1",
        school_name: 'budaya',
    },
    {
        student_id: 682,
        cpr: null,
        registration_date: "1/13/2019",
        first_name: "Wadeeha",
        additional_names: "Abbas Abdulnabi",
        gender: "F",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 1586,
        cpr: '071001026',
        registration_date: "6/23/2018",
        first_name: "Ridha",
        additional_names: "Abbas Ahmed",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 587,
        cpr: '981003524',
        registration_date: "1/13/2019",
        first_name: "Asmah",
        additional_names: "Abbas Abdulnabi",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 701,
        cpr: '071200223',
        registration_date: "1/13/2019",
        first_name: "Ali",
        additional_names: "Abbas Ahmed Abdulla",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 'gurnatah',
        school_name: 'budaya',
    },
    {
        student_id: 1253,
        cpr: '101213298',
        registration_date: "5/24/2017",
        first_name: "Tahera",
        additional_names: "Abbas Ahmed Hassan AlFrsani",
        gender: "F",
        birthdate: "12/16/2010",
        school_grade: "Pri 1",
        school_name: 'gurnatah',
    },
    {
        student_id: 1788,
        cpr: '071001026',
        registration_date: "1/13/2019",
        first_name: "Mohamed Hussain",
        additional_names: "Mohamed Jawad Taha",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 6,
        school_name: 'budaya',
    },
    {
        student_id: 1788,
        cpr: '071001026',
        registration_date: "1/13/2019",
        first_name: "Mohamed Hussain",
        additional_names: "Mohamed Jawad Taha",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 6,
        school_name: 'budaya',
    },
    {
        student_id: 791,
        cpr: '980408032',
        registration_date: "1/13/2019",
        first_name: "Mariam",
        additional_names: "Abaas Mohammed Habib",
        gender: "F",
        birthdate: "10/7/2007",
        school_grade: "Pri 6",
        school_name: 'budaya',
    },
    {
        student_id: 1213,
        cpr: '091005515',
        registration_date: "2/21/2017",
        first_name: "Abdulla",
        additional_names: "Abbas Abdulla Ahmed Jassim",
        gender: "M",
        birthdate: "10/8/2009",
        school_grade: "Pri 2",
        school_name: "Barbar Primary School",
    },
    {
        student_id: 435,
        cpr: '080604617',
        registration_date: "10/13/2018",
        first_name: "Kawthar",
        additional_names: "Abbas Abdulla Ali",
        gender: "F",
        birthdate: "6/14/2008",
        school_grade: "Pri 1",
        school_name: 'budaya',
    },
    {
        student_id: 682,
        cpr: null,
        registration_date: "1/13/2019",
        first_name: "Wadeeha",
        additional_names: "Abbas Abdulnabi",
        gender: "F",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 1586,
        cpr: '071001026',
        registration_date: "6/23/2018",
        first_name: "Ridha",
        additional_names: "Abbas Ahmed",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 587,
        cpr: '981003524',
        registration_date: "1/13/2019",
        first_name: "Asmah",
        additional_names: "Abbas Abdulnabi",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 701,
        cpr: '071200223',
        registration_date: "1/13/2019",
        first_name: "Ali",
        additional_names: "Abbas Ahmed Abdulla",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 'gurnatah',
        school_name: 'budaya',
    },
    {
        student_id: 1253,
        cpr: '101213298',
        registration_date: "5/24/2017",
        first_name: "Tahera",
        additional_names: "Abbas Ahmed Hassan AlFrsani",
        gender: "F",
        birthdate: "12/16/2010",
        school_grade: "Pri 1",
        school_name: 'gurnatah',
    },
    {
        student_id: 1788,
        cpr: '071001026',
        registration_date: "1/13/2019",
        first_name: "Mohamed Hussain",
        additional_names: "Mohamed Jawad Taha",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 6,
        school_name: 'budaya',
    },
    {
        student_id: 1788,
        cpr: '071001026',
        registration_date: "1/13/2019",
        first_name: "Mohamed Hussain",
        additional_names: "Mohamed Jawad Taha",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 6,
        school_name: 'budaya',
    },
    {
        student_id: 791,
        cpr: '980408032',
        registration_date: "1/13/2019",
        first_name: "Mariam",
        additional_names: "Abaas Mohammed Habib",
        gender: "F",
        birthdate: "10/7/2007",
        school_grade: "Pri 6",
        school_name: 'budaya',
    },
    {
        student_id: 1213,
        cpr: '091005515',
        registration_date: "2/21/2017",
        first_name: "Abdulla",
        additional_names: "Abbas Abdulla Ahmed Jassim",
        gender: "M",
        birthdate: "10/8/2009",
        school_grade: "Pri 2",
        school_name: "Barbar Primary School",
    },
    {
        student_id: 435,
        cpr: '080604617',
        registration_date: "10/13/2018",
        first_name: "Kawthar",
        additional_names: "Abbas Abdulla Ali",
        gender: "F",
        birthdate: "6/14/2008",
        school_grade: "Pri 1",
        school_name: 'budaya',
    },
    {
        student_id: 682,
        cpr: null,
        registration_date: "1/13/2019",
        first_name: "Wadeeha",
        additional_names: "Abbas Abdulnabi",
        gender: "F",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 1586,
        cpr: '071001026',
        registration_date: "6/23/2018",
        first_name: "Ridha",
        additional_names: "Abbas Ahmed",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 587,
        cpr: '981003524',
        registration_date: "1/13/2019",
        first_name: "Asmah",
        additional_names: "Abbas Abdulnabi",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: "Pri 2",
        school_name: 'budaya',
    },
    {
        student_id: 701,
        cpr: '071200223',
        registration_date: "1/13/2019",
        first_name: "Ali",
        additional_names: "Abbas Ahmed Abdulla",
        gender: "M",
        birthdate: "10/7/2007",
        school_grade: 'gurnatah',
        school_name: 'budaya',
    },
    {
        student_id: 1253,
        cpr: '101213298',
        registration_date: "5/24/2017",
        first_name: "Tahera",
        additional_names: "Abbas Ahmed Hassan AlFrsani",
        gender: "F",
        birthdate: "12/16/2010",
        school_grade: "Pri 1",
        school_name: 'gurnatah',
    },
]



