export {
  logIn,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  logOut,
  LOGOUT_START,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,
  loggedIn,
  LOGGEDIN_START,
  LOGGEDIN_SUCCESS,
  LOGGEDIN_FAILURE

} from './authenticationActions.js';

export {
  getStudentTable,
  FETCH_STUDENTS_START,
  FETCH_STUDENTS_SUCCESS,
  FETCH_STUDENTS_FAILURE,
  CREATE_NEW_STUDENT_START,
  CREATE_NEW_STUDENT_SUCCESS,
  CREATE_NEW_STUDENT_FAILURE,
  FETCH_COURSES_BY_STUDENT_START,
  FETCH_COURSES_BY_STUDENT_SUCCESS,
  FETCH_COURSES_BY_STUDENT_FAILURE
} from './adminDashboardActions/students/studentsActions';

export {
  getCourseTable,
  FETCH_COURSES_START,
  FETCH_COURSES_SUCCESS,
  FETCH_COURSES_FAILURE,

  getCourseById,
  FETCH_COURSEBYID_START,
  FETCH_COURSEBYID_SUCCESS,
  FETCH_COURSEBYID_FAILURE,

  // editCouseById,

  GET_TERM_TABLE_SUCCESS,
  GET_COURSE_TYPE_TABLE_SUCCESS,
  GET_GROUP_TYPE_TABLE_SUCCESS,
  GET_SCHOOL_GRADE_TABLE_SUCCESS,
  GET_LEVEL_TABLE_SUCCESS,
  GET_COURSE_SCHEDULE_TABLE_SUCCESS,
  GET_ROOM_TABLE_SUCCESS,
  GET_TEACHER_TABLE_SUCCESS,

  CREATE_NEW_COURSE_START,
  CREATE_NEW_COURSE_SUCCESS,
  CREATE_NEW_COURSE_FAILURE,

  EDIT_COURSEBYID_START,
  EDIT_COURSEBYID_SUCCESS,
  EDIT_COURSEBYID_FAILURE

} from './adminDashboardActions/courses/courseAction';

// export {
//   toggleEditComponent,
//   getStudentById,
//   FETCH_STUDENTBYID_START,
//   FETCH_STUDENTBYID_SUCCESS,
//   FETCH_STUDENTBYID_FAILURE,

//   editStudentById,
//   EDIT_STUDENTBYID_START,
//   EDIT_STUDENTBYID_SUCCESS,
//   EDIT_STUDENTBYID_FAILURE,
  
//   deleteStudentById,
//   DELETE_STUDENTBYID_START,
//   DELETE_STUDENTBYID_SUCCESS,
//   DELETE_STUDENTBYID_FAILURE,
// } from './adminDashboardActions/studentByIdAction.js'