export {
  logIn,
  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  logOut,
  LOGOUT_START,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,
  loggedIn,
  LOGGEDIN_START,
  LOGGEDIN_SUCCESS,
  LOGGEDIN_FAILURE

} from './authenticationActions.js';

export {
  getStudentTable,
  FETCH_STUDENTS_START,
  FETCH_STUDENTS_SUCCESS,
  FETCH_STUDENTS_FAILURE,
  CREATE_NEW_STUDENT_START,
  CREATE_NEW_STUDENT_SUCCESS,
  CREATE_NEW_STUDENT_FAILURE,
  FETCH_COURSES_BY_STUDENT_START,
  FETCH_COURSES_BY_STUDENT_SUCCESS,
  FETCH_COURSES_BY_STUDENT_FAILURE,
  GET_PLACEMENT_EXAM_START,
  GET_PLACEMENT_EXAM_SUCCESS,
  GET_PLACEMENT_EXAM_FAILURE,
  GET_PROGRESS_REPORTS_START,
  GET_PROGRESS_REPORTS_SUCCESS,
  GET_PROGRESS_REPORTS_FAILURE,
  GET_TEACHERS_TABLE_START,
  GET_TEACHERS_TABLE_SUCCESS,
  GET_COURSE_INFO_START,
  GET_COURSE_INFO_SUCCESS,
  EDIT_PROGRESS_REPORT_SUCCESS,
  EDIT_PROGRESS_REPORT_FAILURE

} from './adminDashboardActions/students/studentsActions';

export {
  getCourseTable,
  FETCH_COURSES_START,
  FETCH_COURSES_SUCCESS,
  FETCH_COURSES_FAILURE,

  getCourseById,
  FETCH_COURSEBYID_START,
  FETCH_COURSEBYID_SUCCESS,
  FETCH_COURSEBYID_FAILURE,

  // editCouseById,

  GET_TERM_TABLE_SUCCESS,
  GET_COURSE_TYPE_TABLE_SUCCESS,
  GET_GROUP_TYPE_TABLE_SUCCESS,
  GET_SCHOOL_GRADE_TABLE_SUCCESS,
  GET_LEVEL_TABLE_SUCCESS,
  GET_COURSE_SCHEDULE_TABLE_SUCCESS,
  GET_ROOM_TABLE_SUCCESS,
  GET_TEACHER_TABLE_SUCCESS,

  CREATE_NEW_COURSE_START,
  CREATE_NEW_COURSE_SUCCESS,
  CREATE_NEW_COURSE_FAILURE,

  EDIT_COURSEBYID_START,
  EDIT_COURSEBYID_SUCCESS,
  EDIT_COURSEBYID_FAILURE,

  GET_ENROLLED_STUDENTS_START,
  GET_ENROLLED_STUDENTS_SUCCESS,
  GET_ENROLLED_STUDENTS_FAILURE

} from './adminDashboardActions/courses/courseAction';

export {
  familyRegister,
  FAMILY_REGISTER_START,
  FAMILY_REGISTER_SUCCESS,
  FAMILY_REGISTER_FAILURE
} from "./registrationActions";

export {
  GET_FAMILY_ID_START,
  GET_FAMILY_ID_SUCCESS,
  GET_FAMILY_ID_FAILURE,
  GET_CHILDREN_START,
  GET_CHILDREN_SUCCESS,
  GET_CHILDREN_FAILURE,
  GET_PLACEMENT_INFO_START,
  GET_PLACEMENT_INFO_SUCCESS,
  GET_PLACEMENT_INFO_FAILURE,
  GET_COURSES_START,
  GET_COURSES_SUCCESS,
  GET_COURSES_FAILURE,
  ADD_NEW_STUDENT_START,
  ADD_NEW_STUDENT_SUCCESS,
  ADD_NEW_STUDENT_FAILURE
} from "./parentDashboardActions/parentDashboard/ParentDashboardActions";